/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ThirdpageIndexImport } from './routes/thirdpage/index'
import { Route as SecondpageIndexImport } from './routes/secondpage/index'
import { Route as MastermindIndexImport } from './routes/mastermind/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThirdpageIndexRoute = ThirdpageIndexImport.update({
  id: '/thirdpage/',
  path: '/thirdpage/',
  getParentRoute: () => rootRoute,
} as any)

const SecondpageIndexRoute = SecondpageIndexImport.update({
  id: '/secondpage/',
  path: '/secondpage/',
  getParentRoute: () => rootRoute,
} as any)

const MastermindIndexRoute = MastermindIndexImport.update({
  id: '/mastermind/',
  path: '/mastermind/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/mastermind/': {
      id: '/mastermind/'
      path: '/mastermind'
      fullPath: '/mastermind'
      preLoaderRoute: typeof MastermindIndexImport
      parentRoute: typeof rootRoute
    }
    '/secondpage/': {
      id: '/secondpage/'
      path: '/secondpage'
      fullPath: '/secondpage'
      preLoaderRoute: typeof SecondpageIndexImport
      parentRoute: typeof rootRoute
    }
    '/thirdpage/': {
      id: '/thirdpage/'
      path: '/thirdpage'
      fullPath: '/thirdpage'
      preLoaderRoute: typeof ThirdpageIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mastermind': typeof MastermindIndexRoute
  '/secondpage': typeof SecondpageIndexRoute
  '/thirdpage': typeof ThirdpageIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mastermind': typeof MastermindIndexRoute
  '/secondpage': typeof SecondpageIndexRoute
  '/thirdpage': typeof ThirdpageIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/mastermind/': typeof MastermindIndexRoute
  '/secondpage/': typeof SecondpageIndexRoute
  '/thirdpage/': typeof ThirdpageIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mastermind' | '/secondpage' | '/thirdpage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mastermind' | '/secondpage' | '/thirdpage'
  id: '__root__' | '/' | '/mastermind/' | '/secondpage/' | '/thirdpage/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MastermindIndexRoute: typeof MastermindIndexRoute
  SecondpageIndexRoute: typeof SecondpageIndexRoute
  ThirdpageIndexRoute: typeof ThirdpageIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MastermindIndexRoute: MastermindIndexRoute,
  SecondpageIndexRoute: SecondpageIndexRoute,
  ThirdpageIndexRoute: ThirdpageIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/mastermind/",
        "/secondpage/",
        "/thirdpage/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/mastermind/": {
      "filePath": "mastermind/index.tsx"
    },
    "/secondpage/": {
      "filePath": "secondpage/index.tsx"
    },
    "/thirdpage/": {
      "filePath": "thirdpage/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
