/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SecondpageIndexImport } from './routes/secondpage/index'
import { Route as FirstpageIndexImport } from './routes/firstpage/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SecondpageIndexRoute = SecondpageIndexImport.update({
  id: '/secondpage/',
  path: '/secondpage/',
  getParentRoute: () => rootRoute,
} as any)

const FirstpageIndexRoute = FirstpageIndexImport.update({
  id: '/firstpage/',
  path: '/firstpage/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/firstpage/': {
      id: '/firstpage/'
      path: '/firstpage'
      fullPath: '/firstpage'
      preLoaderRoute: typeof FirstpageIndexImport
      parentRoute: typeof rootRoute
    }
    '/secondpage/': {
      id: '/secondpage/'
      path: '/secondpage'
      fullPath: '/secondpage'
      preLoaderRoute: typeof SecondpageIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/firstpage': typeof FirstpageIndexRoute
  '/secondpage': typeof SecondpageIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/firstpage': typeof FirstpageIndexRoute
  '/secondpage': typeof SecondpageIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/firstpage/': typeof FirstpageIndexRoute
  '/secondpage/': typeof SecondpageIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/firstpage' | '/secondpage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/firstpage' | '/secondpage'
  id: '__root__' | '/' | '/firstpage/' | '/secondpage/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FirstpageIndexRoute: typeof FirstpageIndexRoute
  SecondpageIndexRoute: typeof SecondpageIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirstpageIndexRoute: FirstpageIndexRoute,
  SecondpageIndexRoute: SecondpageIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/firstpage/",
        "/secondpage/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/firstpage/": {
      "filePath": "firstpage/index.tsx"
    },
    "/secondpage/": {
      "filePath": "secondpage/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
